### ISSUE TITLE
Update so that it can use the slim loader

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-electron#22]
In production mode.

**Comment by m-mujica** [comment]
More or less the same story as in steal-cordova...

It just works without major changes

```javascript
var path = require("path");
var stealElectron = require("steal-electron");
var slim = require("steal-tools/lib/build/slim");

var buildPromise = slim(
  {
    main: "myhub",
    config: path.join(__dirname, "package.json!npm")
  },
  {
    target: ["web", "node"],
    minify: false
  }
);

var electronOptions = {
  buildDir: "./build",
  platforms: ["darwin"],
  main: "electron-main.js",
  electronVersion: "1.6.11",
  files: ["dist/**/*", "index.html"]
};

buildPromise
  .then(function(buildResult) {
    return stealElectron(electronOptions, buildResult.web);
  })
  .catch(function(err) {
    console.log("Uh-oh! something went wrong: ", err);
  });
```

![myhub](https://user-images.githubusercontent.com/724877/28936674-ac304fdc-7845-11e7-8a19-8e4ba3b21796.png)

![myhub-2](https://user-images.githubusercontent.com/724877/28936687-b22960cc-7845-11e7-8040-a6fe519386da.png)

![myhub-3](https://user-images.githubusercontent.com/724877/28936696-b79fdf40-7845-11e7-872b-e8b4fb0dfd52.png)

**Comment by m-mujica** [comment]
I did notice that everytime I run `stealElectron.build` it mutates my application `package.json`, it changes the main attribute which is not cool (looking into that)

@matthewp would you like me to update the slim loader guide with the steps to create cordova/electron builds, or would rather have me work on something else?

**Comment by matthewp** [comment]
@m-mujica can this be closed?
